apiVersion: v1
items:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    annotations:
      helm.sh/created: "1522680472"
    creationTimestamp: 2018-04-02T14:47:52Z
    generation: 1
    labels:
      app: pgset
      chart: statefulset-1
      name: pgset
    name: pgset
    namespace: default
    resourceVersion: "18214"
    selfLink: /apis/apps/v1beta1/namespaces/default/statefulsets/pgset
    uid: d238a60b-3684-11e8-bc39-02f4cb1be06a
  spec:
    podManagementPolicy: OrderedReady
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: pgset
    serviceName: pgset
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pgset
      spec:
        containers:
        - env:
          - name: PGHOST
            value: /tmp
          - name: PG_PRIMARY_USER
            value: primaryuser
          - name: PG_MODE
            value: set
          - name: PG_PRIMARY_HOST
            value: pgset-primary
          - name: PG_REPLICA_HOST
            value: pgset-replica
          - name: PG_PRIMARY_PORT
            value: "5432"
          - name: PG_PRIMARY_PASSWORD
            value: password
          - name: PG_USER
            value: testuser
          - name: PG_PASSWORD
            value: password
          - name: PG_DATABASE
            value: userdb
          - name: PG_ROOT_PASSWORD
            value: password
          image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
          imagePullPolicy: IfNotPresent
          name: pgset
          ports:
          - containerPort: 5432
            name: postgres
            protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /pgdata
            name: pgdata
          - mountPath: /backup
            name: backup
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: pgset-sa
        serviceAccountName: pgset-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: pgdata
        - emptyDir: {}
          name: backup
    updateStrategy:
      type: OnDelete
  status:
    collisionCount: 16
    currentRevision: pgset-54c6765c7
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updateRevision: pgset-54c6765bd
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
